using FGOCore.FGOCoreCode.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;

namespace MorganBerserker.MorganBerserkerCode.Cards.Special;

/// <summary>
/// Arma del Caballero (骑士的武器) — token generated by Memory of Londinium:
/// "las espadas de los caballeros del pasado, presente y futuro". 0⚡, Exhaust.
/// </summary>
public sealed class KnightsArm() : MorganCard(0, CardType.Attack, CardRarity.Event, TargetType.AnyEnemy)
{
    /// <summary>Preview animado al manifestar cada Arma (el ecosistema usa 0.8f para estos tokens).</summary>
    public const float ManifestPreviewTime = 0.8f;

    /// <summary>
    /// Añade <paramref name="count"/> Armas del Caballero a la mano de <paramref name="creature"/>,
    /// con su preview animado. Centraliza el patrón "crear + AddGeneratedCardToCombat + Preview"
    /// que estaba duplicado en WinterCourtPower / MemoryOfLondinium / CallOfTheFairyKnights /
    /// ViviansGift (delega en el helper común <see cref="ManifestCards.ManifestToHand{T}"/>).
    /// </summary>
    public static async Task AddToHand(Creature creature, int count)
    {
        for (var i = 0; i < count; i++)
        {
            await ManifestCards.ManifestToHand<KnightsArm>(creature, ManifestPreviewTime);
        }
    }

    public override IEnumerable<CardKeyword> CanonicalKeywords => [CardKeyword.Exhaust];

    protected override IEnumerable<DynamicVar> CanonicalVars => [new DamageVar(5m, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target);
        await DamageCmd.Attack(DynamicVars.Damage.BaseValue).FromCard(this).Targeting(cardPlay.Target)
            .WithHitFx("vfx/vfx_attack_slash")
            .Execute(choiceContext);
    }

    protected override void OnUpgrade()
    {
        DynamicVars.Damage.UpgradeValueBy(3m);
    }
}
